language: csharp
mono: none

notifications:
  email: false

branches:
  only:
    - master

matrix:
  include:
    - os: linux 
      dist: xenial # Ubuntu 16.04
      dotnet: 3.0
    - os: linux
      dist: xenial # Ubuntu 16.04
      dotnet: 3.0
      env: TargetFrameworkOverride=netstandard2.0
    - os: osx
      dotnet: 3.0.100 # For OSX, we need absolute dotnet version until https://github.com/dotnet/core-setup/issues/4187 is resolved
      osx_image: xcode11

before_install:
  - if [ $TRAVIS_OS_NAME = linux ]; then sudo apt-get -qq update; EXTRA_CONSTANT=-p:BuildConstants=NOCONSENSUSLIB; fi
  - if [ $TRAVIS_OS_NAME = osx ]; then ulimit -S -n 4096; EXTRA_CONSTANT=-p:BuildConstants=NOCONSENSUSLIB; fi

script:
  - dotnet build ./NBitcoin.Tests/NBitcoin.Tests.csproj /p:TargetFrameworkOverride=$TargetFrameworkOverride -c Release -f netcoreapp3.0  $EXTRA_CONSTANT
  - dotnet test --no-build -v n -c Release -f netcoreapp3.0 ./NBitcoin.Tests/NBitcoin.Tests.csproj --filter "RestClient=RestClient|RPCClient=RPCClient|Protocol=Protocol|Core=Core|UnitTest=UnitTest" -p:ParallelizeTestCollections=false  < /dev/null
